### PR TITLE
Support hashing of GIFs

### LINKED ISSUE #52: GIFs cannot be hashed
## Problem

The following MWE

```markdown
![Earth](./Rotating_earth_(large).gif)
```

with the following (any) local GIF fails to convert.

Rotating_earth_(large)

## Reason

https://github.com/phseiff/github-flavored-markdown-to-html/blob/a3f21df18351afd5aeb1aa5bd57f0f5bae6d9b00/src/__init__.py#L609-L610

`list(img.getdata())` returns a simple `list` of `int`s for GIFs instead of a `list` of `tuple`s (PNGs etc).

### PR DESCRIPTION
**Pull request by janniklasrose**
Fixes #52

### CODE REVIEW

**Comment by janniklasrose** [comment]
Tested this locally and it solves the problem, although it is not the most elegant solution.

**Comment by phseiff** [comment]
Hello, and thanks for the pull request (and the corresponding issue)!

I think it would also be good to add the GIF's color profile to the hash, since a two-colored red-and-yellow image and a two-colored black-and-white image with the same motive might otherwise result in the same hash. But I can do that after I merged the pull request, so no need to add this to your PR if you don't want to. :)

I should also probably disable the optional image compression for GIFs since I can't foresee what it will do for animated ones, and since converting GIF to JPEG is probably actually worse for compression, but that's a different issue.

I will probably merge this in 1-2 days since I don't really have time for testing right now, if that's okay.

**Comment by phseiff** [comment]
> Tested this locally and it solves the problem, although it is not the most elegant solution.

It doesn't seem that unelegant to me, tbh, at least in comparison with the surrounding code :laugh:

Also, thanks again for your valuable contribution.

**Comment by janniklasrose** [comment]
I think it would be worthwhile adding support for the colour profile too, but perhaps in a separate issue together with support for animated GIFs (such as the one in #52, which becomes static).

**Comment by phseiff** [comment]
I merged this and released a new version `v1.17.6` (to which you can update e.g. via `pip3 install --upgrade gh-md-to-html>=1.17.6`) based on it.

The new version
* supports hashing of GIFs by converting them from paletted color mode to RGBA before creating the hash (therefore properly distinguishing between GIFs that differ in their color palette whilst displaying the same shapes and forms, and properly recognizing two identical GIFs with a differently indexed color palette as identical), This means that I had to overwrite your changes, but your contribution is still in GIT nonetheless, so GitHub properly recognizes you as a contributor.
* supports hashing animated GIFs (framerate-sensitive), and supports saving animated GIFs correctly,
* doesn't try to compress GIFs if image compression is enabled anymore.

**Pull request merged**
